### ISSUE TITLE
Filename for GenParamesh module

### ISSUE THREAD

**Issue by bpaniagua** [laurapascal/SPHARM-PDM#2]
@laurapascal:

We have to change the generateCLP parameters of GenParaMesh so GenParaMesh is shown in the Slicer menu and not GenParaMeshCLP. This is just for consistence with the other two modules.

Thank you!

**Comment by laurapascal** [comment]
Fixed with the commit [879990d](https://github.com/laurapascal/SPHARM-PDM/commit/879990d1a3dbd5b84c990601e2f920872eb7a29e).
